import { EsotericDimension } from '../types';

export const ESOTERIC_DIMENSIONS: EsotericDimension[] = [
  {
    dimension: '1D',
    sanskritName: 'भू-तत्व एवं मूल चेतना (Bhū-Tattva)',
    englishTitle: '1st Dimension: The Point & Mineral Consciousness',
    elementTattva: 'पृथ्वी (Earth)',
    planeOfConsciousness: 'अन्नामय कोष (Annamaya Kosha - Gross Matter)',
    description: 'प्रथम आयाम भौतिक द्रव्य, खनिज, रासायनिक तत्व एवं गुरुत्वाकर्षण की नींव है। यह चेतना का सुप्त, स्थिर बिंदु है जहां पदार्थ संगठित होता है।',
    planetaryConnection: 'शनि (Saturn) एवं पृथ्वी - संरचना, अस्थि, धातु और स्थूल सीमाएं।',
    spiritualPractice: 'मूलबंध, भू-स्पर्श, त्राटक, और प्रकृति के साथ मौन जुड़ाव।',
    karmicSignificance: 'संचित कर्म का स्थूल रूप - आनुवंशिक डीएनए और शारीरिक प्रवृत्तियां।',
  },
  {
    dimension: '2D',
    sanskritName: 'प्राण-तत्व एवं सूक्ष्म स्पंदन (Prāṇa-Tattva)',
    englishTitle: '2nd Dimension: Plane of Instinct & Biological Flow',
    elementTattva: 'जल (Water)',
    planeOfConsciousness: 'प्राणमय कोष (Pranamaya Kosha - Vital Energy)',
    description: 'द्वितीय आयाम वनस्पति, जैव ऊर्जा, जैविक लय और ध्रुवीयता (Polarity) का क्षेत्र है। यह भावना और जीवन-रस का प्रवाह है।',
    planetaryConnection: 'चन्द्र (Moon) एवं शुक्र (Venus) - जल तत्व, रस, जनन शक्ति, स्वप्नावस्था।',
    spiritualPractice: 'प्राणायाम (नाड़ी शोधन), कुंडलिनी स्पंदन, जल तर्पण।',
    karmicSignificance: 'प्रारब्ध की अंतर्धारा - सहज इच्छाएं, आकर्षण और जैव-प्रवृत्तियां।',
  },
  {
    dimension: '3D',
    sanskritName: 'मनस् एवं त्रिआयामी संसार (Manas / Jagat)',
    englishTitle: '3rd Dimension: Physical Matrix & Linear Reality',
    elementTattva: 'अग्नि (Fire)',
    planeOfConsciousness: 'मनोमय कोष (Manomaya Kosha - Mental Matrix)',
    description: 'वर्तमान मानव अनुभव का भौतिक क्षेत्र जहां लंबाई, चौड़ाई, ऊंचाई और काल का भ्रम (Maya) निर्मित होता है। अहंकार (Ego) और कर्ता-भाव का केंद्र।',
    planetaryConnection: 'सूर्य (Surya) एवं मंगल (Mars) - इच्छाशक्ति, पराक्रम, अहं-भाव और दृश्य जगत।',
    spiritualPractice: 'कर्म योग, धर्म-सम्मत आचरण, स्वाध्याय, और एकाग्रता।',
    karmicSignificance: 'क्रियमाण कर्म (Present Actions) - वर्तमान में किए जा रहे संकल्प और निर्णय।',
  },
  {
    dimension: '4D',
    sanskritName: 'काल एवं सूक्ष्म सूक्ष्मलोक (Kāla & Astral Plane)',
    englishTitle: '4th Dimension: Time Vector & Astral Realm',
    elementTattva: 'वायु (Air)',
    planeOfConsciousness: 'विज्ञानमय कोष (Vijnanamaya Kosha - Astral/Intuitive)',
    description: 'काल का प्रवाह, स्वप्न लोक, विचार रूप (Thoughtforms), और मृत्यु-उपरांत की सूक्ष्म यात्राएं। यहां समय अब रेखीय नहीं बल्कि एक नदी की भांति बहता है।',
    planetaryConnection: 'राहु (Rahu) एवं बुध (Mercury) - सूक्ष्म विचार, समय विलोपन, सूक्ष्म लोक संचार।',
    spiritualPractice: 'योग निद्रा, सुप्त चेतना जागरण (Lucid Dreaming), आकाश दर्शन।',
    karmicSignificance: 'आगम कर्म (Future Projections) - सूक्ष्म विचारों द्वारा भविष्य के बीज बोना।',
  },
  {
    dimension: '5D',
    sanskritName: 'आकाश एवं कारण शरीर (Ākāśa & Causal Body)',
    englishTitle: '5th Dimension: Akashic Field & Unconditional Resonance',
    elementTattva: 'आकाश (Ether / Space)',
    planeOfConsciousness: 'आनंदमय कोष (Anandamaya Kosha - Causal Plane)',
    description: 'द्वैत से परे प्रेम, आकाशीय अभिलेख (Akashic Records), अंतर्ज्ञान, और आत्म-पहचान का उच्च स्तर। यहां समस्त आत्माएं एक सूत्र में जुड़ी अनुभव होती हैं।',
    planetaryConnection: 'बृहस्पति (Jupiter) एवं केतु (Ketu) - उच्च ज्ञान, मोक्ष, अखंड आनंद।',
    spiritualPractice: 'अजपा-जप, नाद योग, अनाहत चक्र ध्यान, सर्वभूतेषु आत्मवत् भाव।',
    karmicSignificance: 'कर्म का विसर्जन - कारण शरीर की शुद्धि और जन्म-मरण चक्र की ग्रंथियों का भेदन।',
  },
  {
    dimension: '6D',
    sanskritName: 'पवित्र ज्यामिति एवं देवलोक (Deva-Loka & Sacred Geometry)',
    englishTitle: '6th Dimension: Sacred Geometries & Archetypal Blueprints',
    elementTattva: 'महत्-तत्व (Cosmic Intellect)',
    planeOfConsciousness: 'हिरण्यगर्भ (Cosmic Golden Womb)',
    description: 'ब्रह्मांडीय गणित, श्री यंत्र की मूल संरचना, और देवताओं व ग्रहों के शुद्ध ऊर्जावान स्वरूप (Archetypes) का स्तर। समस्त भौतिक संरचनाएं यहीं से प्रतिध्वनित होती हैं।',
    planetaryConnection: 'नवग्रहों के अधिष्ठाता देवता, श्री त्रिपुर सुंदरी एवं महादेव।',
    spiritualPractice: 'यंत्र साधना, मंडाला ध्यान, ज्यामितीय बीज मंत्र लय।',
    karmicSignificance: 'ब्रह्मांडीय संरचना के साथ आत्मा के मूल ब्लूप्रिंट का मिलान।',
  },
  {
    dimension: '7D',
    sanskritName: 'शब्द ब्रह्म एवं ओंकार नाद (Śabda Brahman)',
    englishTitle: '7th Dimension: Universal Sound & Rishi Consciousness',
    elementTattva: 'नाद / स्फोट (Pranava / Omkara)',
    planeOfConsciousness: 'ऋषि चेतना (Saptrishi & Cosmic Sound)',
    description: 'समस्त सृष्टि का मूल कंपन - प्रणव "ॐ" और अनाहत ध्वनि। सप्तर्षि मंडल और वेदों की ऋचाओं का प्रत्यक्ष स्फुरण।',
    planetaryConnection: 'परम गुरु तत्व, बृहस्पति की परा शक्ति, आदिशक्ति की परा वाणी।',
    spiritualPractice: 'ॐकार ध्वनि महासाधना, नादानुसंधान, महामौन।',
    karmicSignificance: 'आत्मा के संपूर्ण कर्म बीज का परा-ध्वनि में भस्म होना।',
  },
  {
    dimension: '8D',
    sanskritName: 'अनंत प्रकाश एवं तारकीय जाल (Tārakā Jāla)',
    englishTitle: '8th Dimension: Galactic Core & Universal Light Matrix',
    elementTattva: 'ज्योति (Pure Divine Light)',
    planeOfConsciousness: 'ईश्वर चेतना (Sovereign Cosmic Light)',
    description: 'आकाशगंगाओं के केंद्रीय सूर्य और शुद्ध प्रकाश किरणों का जाल। यह व्यक्तिगत चेतना को ब्रह्मांडीय चेतना में एकीकृत करता है।',
    planetaryConnection: 'महा-सूर्य (Central Galactic Sun) - आदित्य मंडल की चरम पराकाष्ठा।',
    spiritualPractice: 'गायत्री महामंत्र का परा-अवस्था में ध्यान, सहस्त्रार भेदन।',
    karmicSignificance: 'वैयक्तिक कर्म से सामूहिक तारकीय चेतना में रूपांतरण।',
  },
  {
    dimension: '9D',
    sanskritName: 'कालचक्र नियमन एवं महामाया (Kāla Chakra Matrix)',
    englishTitle: '9th Dimension: Time-Grid Oversight & Maha Maya',
    elementTattva: 'महा-प्रकृति (Primordial Nature Matrix)',
    planeOfConsciousness: 'मूल प्रकृति (Prakriti Root)',
    description: 'काल, युग चक्रों (सत्य, त्रेता, द्वापर, कलि) और बहु-ब्रह्मांडों के नियमों का संतुलन केंद्र। महामाया का खेल।',
    planetaryConnection: 'काल भैरव एवं महाकाली - समय और आयामों के अधिपति।',
    spiritualPractice: 'महाकाली / काल भैरव साधना, कालजयी ध्यान।',
    karmicSignificance: 'समय चक्र से पूर्ण मुक्ति (Transcendence of Kala).',
  },
  {
    dimension: '10D',
    sanskritName: 'विराट पुरुष एवं समस्त संभावना (Virāṭ Puruṣa)',
    englishTitle: '10th Dimension: Multi-Cosmic Omnipresence',
    elementTattva: 'सर्व-संभावना (Omni-potentiality)',
    planeOfConsciousness: 'विराट रूप (Cosmic Multi-Form)',
    description: 'गीता के एकादश अध्याय में वर्णित भगवान श्री कृष्ण का विश्वरूप - जहां भूत, वर्तमान और भविष्य के समस्त ब्रह्मांड एक साथ समाहित हैं।',
    planetaryConnection: 'भगवान नारायण का शेषशायी एवं विश्वंभर स्वरूप।',
    spiritualPractice: 'विश्वरूप दर्शन भावना, अहं ब्रह्मास्मि की अनुभूति।',
    karmicSignificance: 'कर्म का अस्तित्व ही समाप्त - केवल विराट लीला का दर्शन।',
  },
  {
    dimension: '11D',
    sanskritName: 'सदाशिव एवं पराशक्ति अद्वैत (Śiva-Śakti Unity)',
    englishTitle: '11th Dimension: The Non-Dual Dance of Siva & Sakti',
    elementTattva: 'चित्-शक्ति (Pure Unmanifest Consciousness)',
    planeOfConsciousness: 'सदाशिव पद (Non-Dual Transcendent)',
    description: 'शिव और शक्ति का परम अद्वैत संगम। यहां प्रकाश और विमर्श, शून्य और पूर्ण एकाकार हो जाते हैं।',
    planetaryConnection: 'परम शिव एवं महापराशक्ति का अनिर्वचनीय स्वरूप।',
    spiritualPractice: 'शिवोऽहम् भाव, अद्वैत वेदांत समाधि।',
    karmicSignificance: 'आत्मा और परमात्मा का अंतिम एकत्व (Kaivalya Mukti).',
  },
  {
    dimension: '12D',
    sanskritName: 'परमब्रह्म सच्चिदानंद एवं कैवल्य (Parabrahman)',
    englishTitle: '12th Dimension: The Absolute Unmanifest & Sat-Chit-Ananda',
    elementTattva: 'निर्गुण निराकार (Beyond All Tattvas / Transcendental)',
    planeOfConsciousness: 'परम ब्रह्म (The Supreme Absolute Reality)',
    description: 'अनिर्वचनीय, अनादि, अनंत, निर्गुण, निराकार, शुद्ध सच्चिदानंद। यहां न कोई देश है, न काल, न ग्रह, न कर्म — केवल शाश्वत सत्य और परमानंद।',
    planetaryConnection: 'समस्त ब्रह्मांडों का मूल स्रोत - परब्रह्म परमेश्वर।',
    spiritualPractice: 'तुरीयातीत समाधि, पूर्ण आत्म-समर्पण, कैवल्य।',
    karmicSignificance: 'मोक्ष की चरम पराकाष्ठा — पुनर्जन्म का सर्वथा अंत।',
  },
];

export const TIME_CONCEPTS = [
  {
    title: 'काल चक्र एवं ब्रह्मांडीय समय (Kala Chakra)',
    hindiTitle: 'काल चक्र एवं महायुग',
    description: 'वैदिक ज्योतिष में काल केवल घड़ी का समय नहीं, बल्कि चेतना के विस्तार की गति है। एक महायुग में 43,20,000 सौर वर्ष होते हैं (सत्य, त्रेता, द्वापर, कलि)।',
    formula: '1 त्रुटि = 29.6 माइक्रोसेकंड → 1 प्राण = 4 सेकंड → 1 घटी = 24 मिनट → 1 अहोरात्र = 24 घंटे',
    relevance: 'आपकी जन्म कुंडली में उस समय के ब्रह्मांडीय आकाश का सटीक स्नैपशॉट संचित होता है।',
  },
  {
    title: 'मुहूर्त विज्ञान (Vedic Chronobiology / Muhurat)',
    hindiTitle: 'मुहूर्त एवं ग्रह होरा',
    description: 'प्रत्येक दिन में 30 मुहूर्त होते हैं (1 मुहूर्त = 48 मिनट)। प्रत्येक दिन में 24 होराएं विशिष्ट ग्रहों द्वारा शासित होती हैं।',
    formula: 'अभिजीत मुहूर्त = दिन के 8वें प्रहर का समय (समस्त दोषों का संहारक)',
    relevance: 'किसी भी शुभ कार्य अथवा रत्न धारण हेतु उपयुक्त मुहूर्त ग्रहों के अनुकूल कंपन को आकर्षित करता है।',
  },
  {
    title: 'आकाश एवं माया (Akasha & Maya Matrix)',
    hindiTitle: 'आकाशीय तरंगे एवं माया',
    description: 'ग्रह किसी पर जादू नहीं करते, बल्कि आकाशीय चुम्बकीय तरंगों (Electromagnetic & Gravitational Resonance) द्वारा मानव मस्तिष्क के न्यूरोट्रांसमीटर को प्रभावित करते हैं।',
    formula: 'कर्म → संस्कार → मानसिक तरंगे → ग्रह संरेखण (Synchronization) → परिणाम',
    relevance: 'मंत्र जाप और ध्यान द्वारा इन तरंगों की आवृत्ति को उच्च 5D/7D आयामों में रूपांतरित किया जा सकता है।',
  },
];

export const KARMIC_MODELS = [
  {
    name: 'संचित कर्म (Sanchita Karma)',
    title: 'The Stored Karmic Warehouse',
    explanation: 'अनंत जन्मों से संचित कर्मों का विशाल भंडार जो अभी फलित नहीं हुआ है।',
    astrologicalIndicator: 'कुंडली का अष्टम (8th) एवं द्वादश (12th) भाव, राहु-केतु अक्ष।',
    remedy: 'वैदिक मंत्र जप, तीर्थाटन, निष्काम कर्म एवं ज्ञान प्राप्ति।',
  },
  {
    name: 'प्रारब्ध कर्म (Prarabdha Karma)',
    title: 'The Destiny Activated in This Lifetime',
    explanation: 'संचित कर्म का वह भाग जिसे इस वर्तमान जन्म में भोगने हेतु चुना गया है। इसे बदला नहीं जा सकता, केवल सुख-दुःख के प्रभाव को सहन करने की शक्ति बढ़ाई जा सकती है।',
    astrologicalIndicator: 'लग्न (1st), नवम (9th) भाग्य भाव एवं वर्तमान विंशोत्तरी महादशा।',
    remedy: 'रत्न धारण, इष्ट देव साधना, ग्रह शांति अनुष्ठान एवं धैर्य।',
  },
  {
    name: 'क्रियमाण कर्म (Kriyamana Karma)',
    title: 'The Present Free Will & Actions',
    explanation: 'वर्तमान क्षण में अपनी स्वतंत्र इच्छाशक्ति (Free Will) द्वारा किए जा रहे कर्म। यह आपके आने वाले भविष्य का निर्माण करते हैं।',
    astrologicalIndicator: 'तृतीय (3rd) भाव (पराक्रम) एवं दशम (10th) कर्म भाव।',
    remedy: 'सत्कर्म, सेवा, स्वाध्याय एवं सकारात्मक संकल्प।',
  },
  {
    name: 'आगम कर्म (Agama Karma)',
    title: 'Future Projections & Intentions',
    explanation: 'भविष्य की योजनाएं, विचार और संकल्प जो आने वाले समय में क्रियमाण कर्म का रूप लेंगे।',
    astrologicalIndicator: 'पंचम (5th) भाव (पूर्व पुण्य व भविष्य दृष्टि) एवं एकादश (11th) भाव।',
    remedy: 'शुभ संकल्प, सात्विक विचार एवं ध्यान।',
  },
];
